version: "3.1"

services:
  ui:
    image: ${REGISTRY}quiz-ui:${TAG}
    ports:
      - "80:5000"
    networks:
      - front-tier
    depends_on: 
      - api
      - results
    logging:
      driver: "json-file"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
        
  api:
    image: ${REGISTRY}quiz-api:${TAG}
    ports:
      - "81:80"
    networks:
      - back-tier
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
      - STREAM_NAME=QuestionAnswers
    logging:
      driver: "json-file"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
  
  results:
    image: ${REGISTRY}quiz-results:${TAG}
    ports:
      - "82:80"
    networks:
      - back-tier
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
      - STREAM_NAME=QuestionAnswers
    logging:
      driver: "json-file"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
  
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
    networks:
      - back-tier
    logging:
      driver: "json-file"
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.40'
          memory: 1500M
        reservations:
          cpus: '0.25'
          memory: 1000M

networks:
  front-tier:
  back-tier: