apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        ports:
        - containerPort: 5432
          name: db
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: changeit
          # valueFrom:
          #   secretKeyRef:
          #     name: db-user-pass
          #     key: db-pass
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: messagebroker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: messagebroker
    spec:
      containers:
      - name: messagebroker
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672 
          name: messagebroker
        - containerPort: 15672 
          name: management
---
apiVersion: v1
kind: Service
metadata:
  name: messagebroker
spec:
  ports:
  - port: 5672
    name: messagebroker
  - port: 15672
    name: management
  selector:
    app: messagebroker
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: messsagebroker
#  annotations:
#   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: quiz-rabbit.io
    http:
      paths:
      - path: /
        backend:
          serviceName: messagebroker
          servicePort: 15672